name: ChaosShop
author: vemacs
version: ${project.version}-${git.branch}-${git.commit.id.abbrev}
main: org.chaospvp.shop.ChaosShop
depend: [Vault]
commands:
  chaosshop:
    description: ChaosShop administration command
    permission: chaosshop.reload
    usage: /chaosshop reload
permissions:
  chaosshop.reload:
    default: op
    